avatar_path = "./avatar"
clear_interval = 60
db_url = "sqlite://appserv.db"
listen = "127.0.0.1:4000"
# 15天过期
session_expire = 1296000
# 1小时刷新token
session_refresh = 3600
smtp_host = "smtp.163.com"
smtp_passwd = "PQHGCAXUAAGMMLCE"
smtp_sender = "toyent@163.com"
